language: node_js
node_js:
- 8.17
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "~/.cache"
install:
- npm ci
- "(cd client && npm ci)"
script:
- npm run ci
before_install:
- openssl aes-256-cbc -K $encrypted_3e247b9e1911_key -iv $encrypted_3e247b9e1911_iv
  -in travis.tar.enc -out travis.tar -d
- openssl aes-256-cbc -K $encrypted_64db488ef579_key -iv $encrypted_64db488ef579_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
notifications:
  email: false
